# Основные настройки отображения
position=top-left               # Позиция (top-left, top-right, bottom-left, bottom-right)
background_alpha=0.5            # Прозрачность фона
font_size=20                    # Размер шрифта

# Логирование
log_path=/tmp/mangohud.log
log_interval=1000  # Лог каждые 1000 мс
toggle_logging=Ctrl+Shift+F6  # Включение/выключение логирования

# HUD
toggle_hud=Ctrl+Shift+F7  # Включение/выключение оверлея

# Перезагрузка конфига (настоящая, без выхода из игры)
reload_cfg=Ctrl+Shift+F8  # Перечитывает конфиг MangoHud на лету

