#!/bin/sh

DOMAIN="ooni.org"
MAX_TIME="3"
TARGET_IP=$(dig +short A "$DOMAIN" | head -n 1)

echo "IP адрес: $TARGET_IP"

echo "Обычный запрос"
curl "https://$DOMAIN" -sS -o /dev/null --max-time "$MAX_TIME" --resolve "$DOMAIN:443:$TARGET_IP" && echo "✅ Успех" || echo "❌ Ошибка"

echo "TLSv1.2"
curl "https://$DOMAIN" --tlsv1.2 -sS -o /dev/null --max-time "$MAX_TIME" --resolve "$DOMAIN:443:$TARGET_IP" && echo "✅ Успех" || echo "❌ Ошибка"

echo "QUIC"
curl "https://$DOMAIN" --http3-only -sS -o /dev/null --max-time "$MAX_TIME" --resolve "$DOMAIN:443:$TARGET_IP" && echo "✅ Успех" || echo "❌ Ошибка"

