#!/usr/bin/env bash

# Список IP-адресов для игнорирования VPN (трафик будет идти через основной интерфейс)
IGNORE_IPS=(
    "1.1.1.1"       # Cloudflare
    "50.114.4.127"
    "185.189.255.58"
    "185.178.210.75"
    "213.59.254.8"
    "140.82.121.3"
    "91.196.35.203"
    "91.196.32.97"
    "94.156.180.112" # mikinol-serv
    "178.141.217.176" # Я
    "213.59.253.7"
    "84.201.174.160" # yonote
    "95.143.178.250" # yonote
    "94.156.180.112"
    "213.59.253.7"

    "141.94.99.232"
    "145.239.166.127"
    "85.192.30.142"
    "5.83.140.207"
)

# Интерфейс основной сети (замените enp42s0 на ваш интерфейс, если нужно)
MAIN_INTERFACE="enp42s0"

current_hostname=$(cat /proc/sys/kernel/hostname)

echo $current_hostname
if [[ "$current_hostname" == "mikinol-Lenovo" ]]; then
  MAIN_INTERFACE=wlp2s0
fi
if [[ "$current_hostname" == "InBookY3HMAX" ]]; then
  MAIN_INTERFACE=wlo1
fi

# Шлюз основной сети (замените 192.168.1.1 на ваш шлюз, если нужно)
MAIN_GATEWAY=$(ip route show dev "$MAIN_INTERFACE" | grep "^default" | awk '{print $3}')

# Проверка привилегий (скрипт должен выполняться от имени root)
if [[ $EUID -ne 0 ]]; then
   echo "Этот скрипт должен выполняться с правами root." >&2
   exit 1
fi

# Добавление маршрутов для игнорируемых IP-адресов
for IP in "${IGNORE_IPS[@]}"; do
    echo "Добавление маршрута для $IP через $MAIN_INTERFACE ($MAIN_GATEWAY)"
    ip route add "$IP" via "$MAIN_GATEWAY" dev "$MAIN_INTERFACE"
    if [[ $? -ne 0 ]]; then
        echo "Не удалось добавить маршрут для $IP. Возможно, он уже существует." >&2
    fi
done

# Подтверждение завершения
echo "Настройка завершена. Трафик для указанных IP-адресов будет идти через основной интерфейс."

