#!/usr/bin/env python3
import selectors
import socket
import json
import os

SOCK_PATH = "/tmp/hypr_window_server.sock"

runtime_dir = os.environ.get("XDG_RUNTIME_DIR")
instance_sig = os.environ.get("HYPRLAND_INSTANCE_SIGNATURE")


def setup_server_socket():
    if os.path.exists(SOCK_PATH):
        os.remove(SOCK_PATH)
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    server.setblocking(False) # Важно для селектора
    server.bind(SOCK_PATH)
    server.listen(5)
    return server

def setup_hyprland_event_socket():
    # Сокет событий Hyprland (socket2)
    hypr_sock2 = f"{runtime_dir}/hypr/{instance_sig}/.socket2.sock"
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.connect(hypr_sock2)
    s.setblocking(False)
    return s

sel = selectors.DefaultSelector()
clients = set()

# Регистрируем серверный сокет
server = setup_server_socket()
sel.register(server, selectors.EVENT_READ, data="accept")

hypr_events = setup_hyprland_event_socket()
sel.register(hypr_events, selectors.EVENT_READ, data="hypr_event")

def get_active_window(is_change_noscreenshare: bool = False):
    # Собираем путь к сокету из переменных окружения
    sock_path = f"{runtime_dir}/hypr/{instance_sig}/.socket.sock"
    
    try:
        # Создаем Unix domain socket (AF_UNIX)
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as cl:
            cl.connect(sock_path)
            
            if is_change_noscreenshare:
                # Важно: пробелы вокруг ';' и корректный синтаксис
                cmd = b"[[BATCH]] hl.dispatch(hl.dsp.window.tag({ tag = \"noscreenshare\", window = \"activewindow\" })) ; j/activewindow"
            else:
                cmd = b"j/activewindow"

            cl.sendall(cmd)
            response = cl.recv(16000)

        response = response[response.find(b"{"):]
            
        info = json.loads(response.decode('utf-8'))
        is_noscreenshare = any(tag.startswith("noscreenshare") for tag in info.get("tags", []))
        window_class = info.get("class", "")
        window_title = info.get("title", "")

        if is_noscreenshare:
            return ""
        else:
            return f"{window_class}: {window_title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")}"
    except Exception as ex:
        raise ex

set_hide = False
old_out = ""
hypr_buffer = ""

def broadcast():
    global old_out, set_hide

    output = get_active_window(is_change_noscreenshare=set_hide) + "\n"

    if set_hide:
        set_hide = False

    if output != old_out:
        old_out = output
        for client in list(clients):
            try:
                client.sendall(output.encode())
            except:
                sel.unregister(client)
                client.close()
                clients.remove(client)

try:
    while True:
        events = sel.select(timeout=None)

        for key, mask in events:
            if key.data == "accept":
                # Новое подключение от Waybar
                conn, addr = server.accept()
                conn.setblocking(False)
                sel.register(conn, selectors.EVENT_READ, data="client")
                clients.add(conn)

                if old_out == "":
                    try:
                        old_out = get_active_window() + "\n"
                    except Exception as ex:
                        print(ex)
                
                conn.sendall(old_out.encode())
            elif key.data == "client":
                conn = key.fileobj
                try:
                    data = conn.recv(1024)
                    if data:
                        command = data.decode().strip()
                        if command == "toggle_hide":
                            set_hide = True
                            print("Set hide")
                            try:
                                broadcast()
                            except Exception as ex:
                                print(ex)
                    
                    # В любом случае после получения данных или если клиент закрылся:
                    sel.unregister(conn)
                    conn.close()
                    if conn in clients:
                        clients.remove(conn)
                except (BlockingIOError, InterruptedError):
                    # Эти ошибки мы игнорируем, просто выходим из блока и ждем следующего цикла селектора
                    pass
                except Exception as ex:
                    print(ex)
                    sel.unregister(conn)
                    conn.close()
                    if conn in clients:
                        clients.remove(conn)
            elif key.data == "hypr_event":
                try:
                    raw_data = hypr_events.recv(4096)
                    if not raw_data:
                        raise RuntimeError("Hyprland socket closed")
                    
                    # Декодируем и добавляем в накопленный буфер
                    hypr_buffer += raw_data.decode('utf-8')
                    
                    # Проверяем, есть ли в буфере хотя бы один перенос строки
                    if '\n' in hypr_buffer:
                        # Разделяем: всё до последнего \n — это готовые строки
                        # Всё после последнего \n — это незаконченный кусок (хвост)
                        lines = hypr_buffer.split('\n')
                        hypr_buffer = lines.pop()  # Последний элемент (хвост) уходит обратно в буфер
                        
                        need_update = False
                        for line in lines:
                            if line.startswith("activewindow>>"):
                                need_update = True
                                break
                        
                        if need_update:
                            try:
                                broadcast()
                            except Exception as ex:
                                print(ex)
                            
                except (BlockingIOError, InterruptedError):
                    pass

finally:
    server.close()
    os.remove(SOCK_PATH)
