#!/usr/bin/env python3
import socket
import time
import json
import os

CHECK_INTERVAL = 0.05

runtime_dir = os.environ.get("XDG_RUNTIME_DIR")
instance_sig = os.environ.get("HYPRLAND_INSTANCE_SIGNATURE")


def get_active_window_json():
    # Собираем путь к сокету из переменных окружения
    sock_path = f"{runtime_dir}/hypr/{instance_sig}/.socket.sock"

    # Создаем Unix domain socket (AF_UNIX)
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as client:
        client.connect(sock_path)
            
        client.sendall(b"j/activewindow")
            
        response = client.recv(16000)
        return json.loads(response.decode('utf-8'))
            

while True:
    try:
        info = get_active_window_json()

        # Проверяем тег
        if any(tag.startswith("noscreenshare") for tag in info.get("tags", [])):
            print("", flush=True)
        else:
            window_class = info.get("class", "")
            window_title = info.get("title", "")
            print(f"{window_class}: {window_title}", flush=True)

    except Exception:
        # Если что-то пошло не так, выводим пустую строку
        print("Ошибка", flush=True)

    time.sleep(CHECK_INTERVAL)

