#!/usr/bin/env python3

import os
import sys
import json
import signal
import subprocess


MIC = os.environ.get("MIC")
if not MIC:
    print(json.dumps({
        "text": "MIC?",
        "class": "error"
    }))
    sys.exit(1)


def get_state():
    try:
        mute = subprocess.check_output(
            ["pactl", "get-source-mute", MIC],
            text=True
        ).split()[1]

        vol = subprocess.check_output(
            ["pactl", "get-source-volume", MIC],
            text=True
        ).split("/")[1].strip().replace("%", "")

        if mute == "yes":
            return {"text": "muted ", "class": "muted"}

        return {"text": f"{vol}% ", "class": "active"}

    except Exception:
        return {"text": "ERR", "class": "error"}


def cleanup(signum, frame):
    if pactl_proc.poll() is None:
        pactl_proc.terminate()
    sys.exit(0)


signal.signal(signal.SIGINT, cleanup)
signal.signal(signal.SIGTERM, cleanup)
signal.signal(signal.SIGPIPE, cleanup)


# начальный вывод
print(json.dumps(get_state()), flush=True)

# подписка на события
pactl_proc = subprocess.Popen(
    ["pactl", "subscribe"],
    stdout=subprocess.PIPE,
    text=True
)


for line in pactl_proc.stdout:
    if "source" in line:
        print(json.dumps(get_state()), flush=True)

