#!/bin/sh
GEOM=$(slurp 2> /dev/null)
if [ -z "$GEOM" ]; then
    exit 1
fi

QR_TEXT=$(grim -g "$GEOM" - | zbarimg --raw - 2> /dev/null)
if [ -z "$QR_TEXT" ]; then
    notify-send "QR" "Ошибка сканирования"
    exit 1
fi

printf '%s' "$QR_TEXT" | wl-copy
