#!/bin/sh
DEVICE="${DEVICE:-unknown_device}"
GEOM=$(slurp)

if [ -n "$GEOM" ]; then
  grim -g "$GEOM" - | \
  tee "$HOME/Общие/Скриншоты/${DEVICE}_$(date +%Y-%m-%d-%H%M%S).png" | \
  wl-copy --type image/png
fi
