#!/bin/sh

mv ~/storage/Music/SoundRecorder/* ~/storage/Общие/Диктофон/

rm ~/.ssh/config
cp ~/storage/Configs/ssh-config ~/.ssh/config

for f in ~/storage/Pictures/Screenshot/*; do
  mv -- "$f" ~/storage/Общие/Скриншоты/"phone_$(basename "$f" | sed 's/^Screenshot_//')"
done
